---
title: "individual3"
author: "Caitlin Fordell"
date: "3/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(dplyr)
```


```{r}
## downloading defensive data
defense <- read_excel('../ds202_lab4/cyclonesFootball2020.xlsx', sheet='Defensive')
head(defense)
```

```{r}
##downloading offensive data
offense <- read_excel('../ds202_lab4/cyclonesFootball2020.xlsx', sheet='Offensive')
head(offense)
```

```{r}
##downloading biographical data
biography <- read_excel('../ds202_lab4/cyclonesFootball2020.xlsx', sheet='Biography')
head(biography)
```
## Part One
## Question One
```{r}
defense <- rename(defense, 'Opponent'='Opponent_Opponent')
defense$Opponent <- as.factor(defense$Opponent)
defense$Name <- as.factor(defense$Name)

offense <- rename(offense, 'Opponent'='Opponent_Opponent')
offense$Opponent <- as.factor(offense$Opponent)
offense$Name <- as.factor(offense$Name)

biography$Name <- as.factor(biography$Name)
```

## Question 2
```{r}
defense[,3:11] <- sapply(defense[,3:11],as.numeric)
str(defense)

offense[,3:11] <- sapply(offense[,3:11],as.numeric)
str(offense)


biography <- separate(biography, Height, c('feet', 'inches'), sep='-')
biography[,3:5] <- sapply(biography[,3:5],as.numeric)
head(biography)

defClean <- defense
offClean <- offense
bioClean <- biography
```

